[toolchain]
channel = "nightly-2022-07-01"
components = [ "rls-preview", "rust-analysis", "rust-src", "llvm-tools-preview" ]
targets = [ "aarch64-unknown-linux-gnu", "aarch64-unknown-none", "aarch64-pc-windows-msvc" ]