[target.aarch64-sophon-uefi]
runner = ".cargo/run-qemu.sh"

[target.x86_64-unknown-uefi]
runner = ".cargo/run-qemu.sh"

[build]
target = "aarch64-sophon-uefi.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]