cargo-features = ["workspace-inheritance"]

[package]
name = "dev"
version = { workspace = true }
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xshell = { workspace = true }
clap = { workspace = true }
spin = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }
yaml-rust = { workspace = true }
anyhow = "1.0"